/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event_management_system;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
/**
 *
 * @author USER
 */
public class events extends javax.swing.JFrame {
    private java.util.ArrayList<Event> eventsList = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(events.class.getName());
private JPanel scrollPanel;
    /**
     * Creates new form events
     */
    public events() {
        initComponents();
       scrollPanel = new JPanel();
scrollPanel.setLayout(new GridLayout(0,1,5,5));

jScrollPane1.setViewportView(scrollPanel);
         loadEventsFromDB(); // load all events from DB
    refreshEventDisplay(); // show them in GUI
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void loadEventsFromDB() {
    eventsList.clear();
    try (Connection conn = DBConnection.getConnection()) {
        String sql = "SELECT event_id, event_name, place, max_people, priority FROM events";
        java.sql.Statement stmt = conn.createStatement();
        java.sql.ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            String id = rs.getString("event_id"); // optional but recommended
            String name = rs.getString("event_name");
            String place = rs.getString("place");
            int maxPeople = rs.getInt("max_people");
            String priority = rs.getString("priority");
            Event e = new Event(name, place, maxPeople, priority);
            e.setId(id); // if your Event class has an id field
            eventsList.add(e);
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddEvent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Event");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddEvent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddEvent.setText("+");
        btnAddEvent.setBorder(null);
        btnAddEvent.addActionListener(this::btnAddEventActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Event");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddEvent)
                        .addContainerGap())
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void openAddEventDialog() {
    String name = JOptionPane.showInputDialog(this, "Enter Event Name:");
    String place = JOptionPane.showInputDialog(this, "Enter Place:");
    String dateStr = JOptionPane.showInputDialog(this, "Enter Date (yyyy-mm-dd):");
    String maxPeopleStr = JOptionPane.showInputDialog(this, "Enter Maximum Attendees:");
    String priority = JOptionPane.showInputDialog(this, "Enter Priority (High/Medium/Low):");

    if (name != null && place != null && dateStr != null && maxPeopleStr != null && priority != null) {
        try {
            int maxPeople = Integer.parseInt(maxPeopleStr);
            java.sql.Date eventDate = java.sql.Date.valueOf(dateStr); // convert string to SQL date
            String generatedId = null;

            try (Connection conn = DBConnection.getConnection()) {
                // Oracle way: Use RETURNING to get the generated event_id
                String sql = "INSERT INTO events (event_name, place, event_date, priority, max_people) " +
                             "VALUES (?, ?, ?, ?, ?) RETURNING event_id INTO ?";

                java.sql.CallableStatement cs = conn.prepareCall(sql);
                cs.setString(1, name);
                cs.setString(2, place);
                cs.setDate(3, eventDate);
                cs.setString(4, priority);
                cs.setInt(5, maxPeople);
                cs.registerOutParameter(6, java.sql.Types.VARCHAR); // event_id is VARCHAR

                cs.executeUpdate();
                generatedId = cs.getString(6); // NOW you have the correct ID
            }

            // ✅ Add to local list and refresh GUI
            Event newEvent = new Event(name, place, maxPeople, priority);
            newEvent.setId(generatedId); // important!
            eventsList.add(newEvent);
            refreshEventDisplay();

            // ✅ Log the action safely
            int currentUser = Session.getInstance().getUserId();
            ActionLogger.logAction(currentUser, "ADD_EVENT", generatedId, "ACTIVE");

            JOptionPane.showMessageDialog(this, "Event added successfully!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Max Attendees must be a number.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Date format must be yyyy-mm-dd.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }
}

private void refreshEventDisplay() {

    scrollPanel.removeAll();   // NOT jPanel1 !!!

    for (int i = 0; i < eventsList.size(); i++) {

        Event e = eventsList.get(i);

        JPanel row = new JPanel();
        row.add(new JLabel("Name: " + e.getName()));
        row.add(new JLabel("Place: " + e.getPlace()));
        row.add(new JLabel("Max: " + e.getMaxPeople()));
        row.add(new JLabel("Priority: " + e.getPriority()));

        JButton edit = new JButton("Edit");
        int index = i;
        edit.addActionListener(evt -> editEvent(index));
        row.add(edit);

        JButton del = new JButton("Delete");
        del.addActionListener(evt -> deleteEvent(index));
        row.add(del);

        scrollPanel.add(row);
    }

    scrollPanel.revalidate();
    scrollPanel.repaint();
}

private void editEvent(int index) {
    Event e = eventsList.get(index);
    String name = javax.swing.JOptionPane.showInputDialog(this, "Edit Name:", e.getName());
    String place = javax.swing.JOptionPane.showInputDialog(this, "Edit Place:", e.getPlace());
    String maxPeopleStr = javax.swing.JOptionPane.showInputDialog(this, "Edit Max Attendees:", e.getMaxPeople());
    String priority = javax.swing.JOptionPane.showInputDialog(this, "Edit Priority:", e.getPriority());

    try {
        int maxPeople = Integer.parseInt(maxPeopleStr);
        e.setName(name);
        e.setPlace(place);
        e.setMaxPeople(maxPeople);
        e.setPriority(priority);
        refreshEventDisplay();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Max Attendees must be a number.");
    }
}


private void deleteEvent(int index) {
    Event e = eventsList.get(index);
    int currentUser = Session.getInstance().getUserId();

    // 1️⃣ Log the deletion first
    ActionLogger.logAction(currentUser, "DELETE_EVENT", e.getId(), "ACTIVE");

    boolean dbDeleted = true;
    // 2️⃣ Delete from DB
    try (Connection conn = DBConnection.getConnection()) {
        String sql = "DELETE FROM events WHERE event_id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, e.getId());
        ps.executeUpdate();
    } catch (Exception ex) {
        dbDeleted = false;
        System.out.println("DB delete failed — removing from UI anyway");
    }

    // 3️⃣ Remove from UI
    eventsList.remove(index);
    refreshEventDisplay();
}




















    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
openAddEventDialog();
    }//GEN-LAST:event_btnAddEventActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 admin a1 = new admin();
        a1.setVisible(true);
        this.setVisible(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new events().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
