CREATE TABLE action_log (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    action_type VARCHAR2(50) NOT NULL,
    event_id VARCHAR2(5),
    action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_log_user FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_log_event FOREIGN KEY (event_id)
        REFERENCES events(event_id)
);

ALTER TABLE action_log
ADD status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'UNDONE', 'REDONE'));

select * from events;

ALTER TABLE action_log
MODIFY event_id VARCHAR2(100);

DROP TABLE action_log;

select * from action_log;

SELECT table_name
FROM user_tables
WHERE table_name = 'ACTION_LOG';









select * from event_registrations;


select * from users;

